# web port
server:
    port: 8081
    #port: 8081

spring:
    redis:
        database: 0
        host: selegant.synology.me
        lettuce:
            pool:
                max-active: 8   #最大连接数据库连接数,设 0 为没有限制
                max-idle: 8     #最大等待连接中的数量,设 0 为没有限制
                max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
                min-idle: 0     #最小等待连接中的数量,设 0 为没有限制
            shutdown-timeout: 100ms
        password: ''
        port: 36379

# log config
logging:
    config: classpath:logback.xml
    path: /Users/selegant/Downloads/datax/datax/work_files
    #path: ./data/applogs/executor/jobhandler

datax:
    job:
        admin:
            ### datax admin address list, such as "http://address" or "http://address01,http://address02"
            #addresses: http://127.0.0.1:8080
            addresses: http://127.0.0.1:8080/jeecg-boot
        executor:
            appname: datax-executor
            ip:
            #port: 9999
            port: 9999
            ### job log path
            #logpath: ./data/applogs/executor/jobhandler
            logpath: /Users/selegant/Downloads/datax/datax/executor
            ### job log retention days
            logretentiondays: 30
        ### job, access token
        accessToken:

    executor:
        #jsonpath: D:\\temp\\executor\\json\\
        jsonpath: /Users/selegant/Downloads/datax/datax/job/

    #pypath: F:\tools\datax\bin\datax.py
    pypath: /Users/selegant/Downloads/datax/datax/bin/datax.py
